insert into super_heroes (name, height, mass, gender, specie) values ('Luke Skywalker', 172, 77, 'MALE', 'HUMAN');
insert into super_heroes (name, height, mass, gender, specie) values ('C-3PO', 167, 75, 'NA', 'DROID');
insert into super_heroes (name, height, mass, gender, specie) values ('Anakin Skywalker', 188, 84, 'MALE', 'HUMAN');
insert into super_heroes (name, height, mass, gender, specie) values ('Han Solo', 180, 80, 'MALE', 'HUMAN');
insert into super_heroes (name, height, mass, gender, specie) values ('Chewbacca', 228, 112, 'MALE', 'WOOKIE');
insert into super_heroes (name, height, mass, gender, specie) values ('Obi-Wan Kenobi', 182, 77, 'MALE', 'HUMAN');
insert into super_heroes (name, height, mass, gender, specie) values ('Leia Organa', 150, 49, 'FEMALE', 'HUMAN');
insert into super_heroes (name, height, mass, gender, specie) values ('Darth Vader', 202, 136, 'MALE', 'HUMAN');
insert into super_heroes (name, height, mass, gender, specie) values ('R2-D2', 96, 32, 'NA', 'DROID');
insert into super_heroes (name, height, mass, gender, specie) values ('Yoda', 66, 17, 'MALE', 'UNKNOWN');
insert into super_heroes (name, height, mass, gender, specie) values ('Palpatine', 170, 75, 'MALE', 'HUMAN');
